project0914_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from students.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^$', index,name='index')

]

students/urls.py
from django.conf.urls import url
from .views import students_list, student_delete, student_update, student_add


urlpatterns = [
    url(r'^students_list/$', students_list, name='students_list'),
    url(r'^student_delete/(\d+)$', student_delete, name='student_delete'),
    url(r'^student_update/(\d+)$', student_update, name='student_update'),
    url(r'^student_add/$', student_add, name='student_add')
]

students/models.py
from django.db import models
from datetime import datetime

# Create your models here.


# 新建一个班级模型类
class BanClass(models.Model):
    name = models.CharField(max_length=30, verbose_name='班级')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '班级信息'
        verbose_name_plural = verbose_name


# 创建学生信息
class StudentInfo(models.Model):
    name = models.CharField(max_length=30, verbose_name='学生姓名')
    age = models.IntegerField(default=18, verbose_name='学生年龄')
    gender = models.CharField(max_length=10, choices=(('girl', '女'), ('boy', '男')), default='girl', verbose_name='性别')
    banclass = models.ForeignKey(BanClass, verbose_name='所属班级')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '学生信息'
        verbose_name_plural = verbose_name


# 学生详细信息
class StudentDetail(models.Model):
    student_num = models.CharField(max_length=30, verbose_name='学号')
    student_phone = models.CharField(max_length=11, verbose_name='手机')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    studentinfo = models.OneToOneField(StudentInfo, verbose_name='所属学生')

    def __str__(self):
        return self.student_num

    class Meta:
        verbose_name = '学生详细信息'
        verbose_name_plural = verbose_name

students/views.py
from django.shortcuts import render, redirect, reverse
from .models import StudentInfo, BanClass, StudentDetail


# Create your views here.


def index(request):
    return render(request, 'index.html')


def students_list(request):
    all_student = StudentInfo.objects.all()
    return render(request, 'students_list.html',
                  {'all_student': all_student})


def student_delete(request, stu_id):
    if stu_id:
        student = StudentInfo.objects.filter(id=int(stu_id))[0]
        print(student)
        # 删主先删子

        student.studentdetail.delete()  # 主对象.字表类名小写为对应的子对象。
        student.delete()
    return redirect(reverse('students:students_list'))


def student_update(request, stu_id):
    if stu_id:
        student = StudentInfo.objects.filter(id=int(stu_id))[0]  # 返回的是StudentInfo对象
        if request.method == 'GET':
            bans = BanClass.objects.all()
            return render(request, 'student_update.html', {
                'student': student, 'bans': bans})
        else:
            student.name = request.POST.get('stuname', '')
            student.age = int(request.POST.get('stuage', ''))
            student.gender = request.POST.get('stugender', '')
            stunum = request.POST.get('stunum', '')
            stuban = request.POST.get('stuban', '')
            student.banclass = BanClass.objects.filter(name=stuban)[0]  # 子对象与新班级对象关联
            student.save()

            # 原先找出原先的学生的详情的对象，把找出的详情对象中的学号改为新的学号

            studd = StudentDetail.objects.filter(studentinfo=student.id)  # 返回的是列表
            if not studd:  # 说明子表没有相关联的对象
                studd = StudentDetail()
                studd.studentinfo = student  # 将新子表对象与主表对象关联
            else:
                studd = studd[0]  # 取出对象
            studd.student_num = stunum  # 修改了 学号
            studd.save()

        return redirect(reverse('students:students_list'))


def student_add(request):
    if request.method == 'GET':
        bans = BanClass.objects.all()
        return render(request, 'student_add.html', {'bans': bans})
    else:
        # 找到班级对象，将新创建的学生加入
        n = request.POST.get('ban', '')
        ban = BanClass.objects.filter(name=n)[0]

        # 新学生对象，接收数据
        new_student = StudentInfo()
        new_student.name = request.POST.get('name', '')
        new_student.age = int(request.POST.get('age', 0))
        new_student.gender = request.POST.get('gender', '')

        # 学生对象关联班级
        new_student.banclass = ban

        new_student.save()

        # 创建新的学生详细信息对象
        new_stu_det = StudentDetail()
        new_stu_det.student_num = request.POST.get('stunum', '')

        # 关联 学生对象和详情对象
        new_stu_det.studentinfo = new_student  # 个人觉得理解为 给子表的关键字段赋值 更为妥当

        new_stu_det.save()


    return redirect(reverse('students:students_list'))

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>这是首页</h2>
<a href="{% url 'students:students_list' %}">查看学生信息</a>
<a href="{% url 'students:student_add' %}">添加学生信息</a>
</body>
</html>

templates/student_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'students:student_add' %}" method="post">
    {% csrf_token %}
    姓名：<input type="text" name="name">
    年龄：<input type="text" name="age">
    性别: <select name="gender">
    <option value="boy">男</option>
    <option value="gir" selected>女</option>
         </select>
    班级：
    <select name="ban" >
    {% for b in bans %}
        <option value="{{ b.name }}">{{ b.name }}</option>
    {% endfor %}
    </select>

    学号：<input type="text" name="stunum" >
    <input type="submit">
</form>
</body>
</html>

templates/student_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'students:student_update' student.id %}" method="post">
    {% csrf_token %}
    姓名：<input type="text" name="stuname" value="{{ student.name }}">
    年龄：<input type="text" name="stuage" value="{{ student.age }}">
    性别：<select name="stugender">
    <option value="boy" {% if student.gender == 'boy' %}selected{% endif %}>男</option>
    <option value="girl" {% if student.gender == 'girl' %}selected{% endif %}>女</option>
</select>
    学号：<input type="text" name="stunum" value="{{ student.studentdetail.student_num }}">
    班级：<select name="stuban">
    # 有几个班级 显示几个班级
    {% for ban in bans %}
        <option value="{{ ban.name }}" {% if ban == student.banclass %}selected{% endif %}>{{ ban.name }}</option>
    {% endfor %}
</select>
    <input type="submit">
</form>
</body>
</html>

templates/students_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table>
    <tr>
        <th>序号</th>
        <th>姓名</th>
        <th>年龄</th>
        <th>性别</th>
        <th>班级</th>
        <th>学号</th>
        <th>操作</th>
    </tr>
    {% for student in all_student %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ student.name }}</td>
            <td>{{ student.age }}</td>
            <td>{{ student.gender }}</td>
            <td>{{ student.banclass.name }}</td>
            <td>{{ student.studentdetail.student_num }}</td>
            <td>

                <a href="{% url 'students:student_delete' student.id %}">删除</a>
                <a href="{% url 'students:student_update' student.id %}">修改</a>
            </td>
        </tr>
    {% endfor %}
</table>
</body>
</html>